### ISSUE TITLE
Music player in sampler fails with exception

### ISSUE THREAD

**Issue by crschnick** [mkpaz/atlantafx#61]
In the sampler application, when clicking on the music player, you will get the following exception:  

    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	      at atlantafx.sampler@2.0.0/atlantafx.sampler.layout.MainLayer.loadPage(MainLayer.java:176)
	      at atlantafx.sampler@2.0.0/atlantafx.sampler.layout.MainLayer.lambda$initListeners$2(MainLayer.java:114)
	      at javafx.base@20/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	      at javafx.base@20/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	      at javafx.base@20/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	      at javafx.base@20/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	      at javafx.base@20/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	      at atlantafx.sampler@2.0.0/atlantafx.sampler.layout.MainModel.navigate(MainModel.java:316)
	      at atlantafx.sampler@2.0.0/atlantafx.sampler.layout.NavTree.lambda$new$0(NavTree.java:36)
	      at javafx.base@20/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	      at javafx.base@20/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	      at javafx.base@20/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	      at javafx.base@20/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	      at javafx.base@20/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	      at javafx.controls@20/javafx.scene.control.SelectionModel.setSelectedItem(Unknown Source)
	      at javafx.controls@20/javafx.scene.control.MultipleSelectionModelBase.lambda$new$0(Unknown Source)
	      at javafx.base@20/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	      at javafx.base@20/javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(Unknown Source)
	      at javafx.base@20/javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(Unknown Source)
	      at javafx.base@20/javafx.beans.property.IntegerPropertyBase.markInvalid(Unknown Source)
	      at javafx.base@20/javafx.beans.property.IntegerPropertyBase.set(Unknown Source)
	      at javafx.controls@20/javafx.scene.control.SelectionModel.setSelectedIndex(Unknown Source)
	      at javafx.controls@20/javafx.scene.control.MultipleSelectionModelBase.select(Unknown Source)
	      at javafx.controls@20/javafx.scene.control.MultipleSelectionModelBase.clearAndSelect(Unknown Source)
	      at javafx.controls@20/javafx.scene.control.TreeView$TreeViewBitSetSelectionModel.clearAndSelect(Unknown Source)
	      at javafx.controls@20/com.sun.javafx.scene.control.behavior.CellBehaviorBase.simpleSelect(Unknown Source)
	      at javafx.controls@20/com.sun.javafx.scene.control.behavior.CellBehaviorBase.doSelect(Unknown Source)
	      at javafx.controls@20/com.sun.javafx.scene.control.behavior.CellBehaviorBase.mousePressed(Unknown Source)
	      at javafx.controls@20/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	      at javafx.base@20/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	      at javafx.base@20/javafx.event.Event.fireEvent(Unknown Source)
	      at javafx.graphics@20/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	      at javafx.graphics@20/javafx.scene.Scene.processMouseEvent(Unknown Source)
	      at javafx.graphics@20/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	      at javafx.graphics@20/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	      at javafx.graphics@20/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	      at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	      at javafx.graphics@20/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	      at javafx.graphics@20/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	      at javafx.graphics@20/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	      at javafx.graphics@20/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	      at javafx.graphics@20/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	      at javafx.graphics@20/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	      at javafx.graphics@20/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	      at java.base/java.lang.Thread.run(Unknown Source)
      Caused by: java.lang.reflect.InvocationTargetException
	      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	      at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	      at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	      at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	      at atlantafx.sampler@2.0.0/atlantafx.sampler.layout.MainLayer.loadPage(MainLayer.java:150)
	      ... 63 more
      Caused by: java.lang.NoClassDefFoundError: Could not initialize class atlantafx.sampler.page.showcase.musicplayer.Model
	      at atlantafx.sampler@2.0.0/atlantafx.sampler.page.showcase.musicplayer.MusicPlayerPage.<init>(MusicPlayerPage.java:25)
	      ... 69 more
      Caused by: java.lang.ExceptionInInitializerError: Exception java.nio.file.FileSystemNotFoundException: Provider "jar" not installed [in thread "JavaFX Application Thread"]
	      at java.base/java.nio.file.Path.of(Unknown Source)
	      at java.base/java.nio.file.Paths.get(Unknown Source)
	      at atlantafx.sampler@2.0.0/atlantafx.sampler.page.showcase.musicplayer.Model.<clinit>(Model.java:22)
	      ... 70 more

I think you have to require the `jdk.zipfs` module to fix that.

**Comment by mkpaz** [comment]
Thanks, guess I should've tested it more thoroughly.
